#!/bin/bash

# harvester - Startup script for harvester

# chkconfig: 35 85 15
# description: low footprint harvester and parser for events and logs
# processname: harvester
# config: /etc/harvester.conf
# pidfile: /var/run/harvester.pid

. /etc/rc.d/init.d/functions

CONFIGFILE="/etc/harvester.conf"
OPTIONS=" -f $CONFIGFILE"
PIDFILE=/var/run/harvester.pid
LOCKFILE=/var/lock/subsys/harvester
USER=harvester
exec=/usr/bin/harvester


start()
{
  echo -n $"Starting harvester: "
  daemon --pidfile="$PIDFILE" --user "$USER" $exec $OPTIONS
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch $LOCKFILE
}

stop()
{
  echo -n $"Stopping harvester: "
  killproc -p "$PIDFILE" $exec
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
}

restart () {
    stop
    start
}

ulimit -n 12000
RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f $LOCKFILE ] && restart || :
    ;;
  status)
    status -p "$PIDFILE" -l "$LOCKFILE" $exec
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL
